# Generated by Django 4.2.7 on 2023-12-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('ยังไม่ได้ดำเนินการ', 'ยังไม่ได้ดำเนินการ'), ('ขอเสนออนุมัติ', 'ขอเสนออนุมัติ'), ('ระหว่างดำเนินงาน', 'ระหว่างดำเนินงาน'), ('ดำเนินงานเสร็จแล้ว', 'ดำเนินงานเสร็จแล้ว')], max_length=20, null=True),
        ),
    ]
