# Generated by Django 5.0 on 2023-12-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
