# Generated by Django 5.0 on 2023-12-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_member_code_member_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
