# Generated by Django 5.0 on 2024-01-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_member_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
