# Generated by Django 5.0 on 2024-01-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_member_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='withdraw',
            field=models.FloatField(null=True),
        ),
    ]
