# Generated by Django 5.0 on 2024-01-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='detail',
            field=models.CharField(choices=[('ยังไม่ได้ดำเนินการ', 'ยังไม่ได้ดำเนินการ'), ('ขอเสนออนุมัติ', 'ขอเสนออนุมัติ'), ('ระหว่างดำเนินงาน', 'ระหว่างดำเนินงาน'), ('ดำเนินงานเสร็จแล้ว', 'ดำเนินงานเสร็จแล้ว')], max_length=20, null=True),
        ),
    ]
